spring:
  application:
    name: Board

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

# Swagger 설정 수정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan:
    - com.springboot.board.api.v1.controller
    - com.springboot.board.web.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
